plugins/org.polarsys.capella.cybersecurity.ui/plugin.xml
- FunctionalPrimaryAsset will propose Functions and associated Threat
- InformationPrimaryAsset will propose Exchange Items and Associated
Threats
- Threat will propose Threatened Assets and Involved Actors
- Actor will propose Involved Threats
Change-Id: I5d80bf736d24b12b06ba9ebf4c421e0913588d0a
Signed-off-by: Sandu Postaru <sandu.postaru@thalesgroup.com>
=> [555020] Add contributions to the 'Show Related Elements' menu

Jenkinsfile, releng/org.polarsys.capella.cybersecurity.target/capella.target-definition.targetplatform
Change-Id: I7707852e7be2779a2fe5c19c41bf6b675d171728
Signed-off-by: Philippe DUL <philippe.dul@thalesgroup.com>
=> [releng] Add initial Jenkinsfile

plugins/org.polarsys.capella.cybersecurity.sirius.analysis/src/org/polarsys/capella/cybersecurity/sirius/analysis/CybersecurityServices.java
Bug: 559451
Change-Id: I2687572c89614e3edf137725c6a401cbed109daf
Signed-off-by: Philippe DUL <philippe.dul@thalesgroup.com>
=> [559451] Add NPE checks on CapellaServices.getDiagramContainer called by style or decorations

features/org.polarsys.capella.cybersecurity.cdo.feature/build.properties, features/org.polarsys.capella.cybersecurity.cdo.feature/feature.properties, features/org.polarsys.capella.cybersecurity.cdo.feature/feature.xml, features/org.polarsys.capella.cybersecurity.cdo.feature/license.html, features/org.polarsys.capella.cybersecurity.feature/build.properties, features/org.polarsys.capella.cybersecurity.feature/feature.properties, features/org.polarsys.capella.cybersecurity.feature/feature.xml, features/org.polarsys.capella.cybersecurity.feature/license.html
Change-Id: Ibefd2d8d92328ad6fd855632c5d2e91e655a973b
Signed-off-by: Ali AKAR <ali.akar82@gmail.com>
=> [Releng] Added copyright and license to all features

Jenkinsfile, features/org.polarsys.capella.cybersecurity.cdo.feature/feature.xml, features/org.polarsys.capella.cybersecurity.feature/feature.xml, features/org.polarsys.capella.cybersecurity.tests.feature/feature.xml, features/pom.xml, plugins/org.polarsys.capella.cybersecurity.af/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.cybersecurity.af/model/Cybersecurity.vp, plugins/org.polarsys.capella.cybersecurity.business.queries/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.cybersecurity.doc/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.cybersecurity.doc/model/documentation/documentation.afm, plugins/org.polarsys.capella.cybersecurity.fc/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.cybersecurity.helpers/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.cybersecurity.model.cdo/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.cybersecurity.model.edit.decorators/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.cybersecurity.model.edit/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.cybersecurity.model/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.cybersecurity.rcp/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.cybersecurity.sirius.analysis/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.cybersecurity.ui/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.cybersecurity.validation/META-INF/MANIFEST.MF, plugins/pom.xml, pom.xml, releng/org.polarsys.capella.cybersecurity.site/category.xml, releng/org.polarsys.capella.cybersecurity.site/pom.xml, releng/org.polarsys.capella.cybersecurity.target/capella.target-definition.targetplatform, releng/org.polarsys.capella.cybersecurity.target/pom.xml, tests/org.polarsys.capella.cybersecurity.test/META-INF/MANIFEST.MF, tests/org.polarsys.capella.cybersecurity.test/pom.xml
Change-Id: I77fd9827c1eccffe7ba6e09ed6164cebaa6bed84
Signed-off-by: Tu Ton <minhtutonthat@gmail.com>
=> [Releng] Bump version to 0.9.2 and adapt pipeline script to Capella 1.4.x

Jenkinsfile, pom.xml, releng/org.polarsys.capella.cybersecurity.target/capella.target-definition.targetplatform, tests/org.polarsys.capella.cybersecurity.test/pom.xml
Change-Id: Ic99eb68e248d12dfe26320208382f4f41917c5b3
Signed-off-by: Philippe DUL <philippe.dul@thalesgroup.com>
=> [releng] Migrate cybersecurity VP to master

plugins/org.polarsys.capella.cybersecurity.business.queries/plugin.xml, plugins/org.polarsys.capella.cybersecurity.business.queries/src/org/polarsys/capella/cybersecurity/business/queries/FunctionalPrimaryAsset_Members.java, plugins/org.polarsys.capella.cybersecurity.model/src/org/polarsys/capella/cybersecurity/model/CybersecurityQueries.java, plugins/org.polarsys.capella.cybersecurity.model/src/org/polarsys/capella/cybersecurity/model/impl/FunctionalPrimaryAssetImpl.java, plugins/org.polarsys.capella.cybersecurity.sirius.analysis/analysis/cybersecurity.odesign, plugins/org.polarsys.capella.cybersecurity.sirius.analysis/src/org/polarsys/capella/cybersecurity/sirius/analysis/CybersecurityServices.java, plugins/org.polarsys.capella.cybersecurity.ui/plugin.xml, plugins/org.polarsys.capella.cybersecurity.ui/src/org/polarsys/capella/cybersecurity/ui/properties/sections/messages.properties
Rename Functions to "Functions / Functional Chains"  and highlight all
functions and functional exchanges
Change-Id: Iafc5c52edcbb5796887eb87fe3f8ee5bca833e76
=> [569450] Allow to select Functional Chains

plugins/org.polarsys.capella.cybersecurity.sirius.analysis/analysis/cybersecurity.odesign, plugins/org.polarsys.capella.cybersecurity.sirius.analysis/src/org/polarsys/capella/cybersecurity/sirius/analysis/CybersecurityServices.java
Change-Id: Ia2d334af59c6657ca6e19e2e563cfc7a10ab7a19
=> [569574] Functional & Component-based visualization of Supporting Assets

plugins/org.polarsys.capella.cybersecurity.sirius.analysis/src/org/polarsys/capella/cybersecurity/sirius/analysis/CybersecurityServices.java
Change-Id: If48a4e22d216ab281fba3388adbc44519df49de8
=> [569574] Fix for Physical Functions visualization

plugins/org.polarsys.capella.cybersecurity.model/src/org/polarsys/capella/cybersecurity/model/CybersecurityQueries.java, plugins/org.polarsys.capella.cybersecurity.ui/src/org/polarsys/capella/cybersecurity/ui/properties/fields/EnumerationLiterealValueRadioGroup.java, plugins/org.polarsys.capella.cybersecurity.ui/src/org/polarsys/capella/cybersecurity/ui/properties/sections/SecurityNeedsSection.java, plugins/org.polarsys.capella.cybersecurity.ui/src/org/polarsys/capella/cybersecurity/ui/properties/sections/ThreatSection.java
- 4 values in a row for SecurityNeeds in Properties
Change-Id: Ia3e2617ed8dde62f587f64ff278971aa564932fe
=> [569689] Compute Max CIAT of all sub and deployed components

plugins/org.polarsys.capella.cybersecurity.sirius.analysis/src/org/polarsys/capella/cybersecurity/sirius/analysis/CybersecurityServices.java, tests/org.polarsys.capella.cybersecurity.test/src/org/polarsys/capella/cybersecurity/test/diagram/CyberPABDiagramTest.java
Change-Id: I61dafae496b6933619818d0a85c993b3a177e108
=> [569450] Display functions/exchanges with the primary asset color + test

tests/org.polarsys.capella.cybersecurity.test/src/org/polarsys/capella/cybersecurity/test/diagram/CyberPABDiagramTest.java
Change-Id: If5ce729386dd49b24f11a0183b2dab7c093836f5
=> [569450] Information Primary Asset - test

plugins/org.polarsys.capella.cybersecurity.sirius.analysis/analysis/cybersecurity.odesign, plugins/org.polarsys.capella.cybersecurity.sirius.analysis/src/org/polarsys/capella/cybersecurity/sirius/analysis/CybersecurityServices.java
Change-Id: Id88845675bdf44385e17aae5c9018a9333d3859b
=> [569574] Improvement of component highlighting

plugins/org.polarsys.capella.cybersecurity.model/src/org/polarsys/capella/cybersecurity/model/CybersecurityQueries.java
- based on the max SecurityNeeds on allocated functions and exchange
items
Change-Id: If62aec7a2ac8105586b97339c30d5e45f3fead60
=> [569689] Compute Max CIAT on a component

plugins/org.polarsys.capella.cybersecurity.sirius.analysis/src/org/polarsys/capella/cybersecurity/sirius/analysis/CybersecurityServices.java
Change-Id: I2098613a605b6ad50b625c8406a7015e692b9b4d
=> [569574] Fix for Physical Actors

plugins/org.polarsys.capella.cybersecurity.sirius.analysis/src/org/polarsys/capella/cybersecurity/sirius/analysis/CybersecurityAnalysisConstants.java, tests/org.polarsys.capella.cybersecurity.test/src/org/polarsys/capella/cybersecurity/test/diagram/CyberPABDiagram.java, tests/org.polarsys.capella.cybersecurity.test/src/org/polarsys/capella/cybersecurity/test/diagram/CyberPABDiagramTest.java
Change-Id: Icaf9e3a153018e3ce58a9b637dbf716b600d8bf9
=> [569574] Added JUnits

Jenkinsfile
Change-Id: I9bb941ddcbff20e3a4bf62d5f9a769e05d765d87
=> [config] Enable Sonar and tests

Jenkinsfile
Change-Id: Ibea11b8c9b5401154427901c9bcfe2e1a6b27576
=> [config] Run Sonar

plugins/org.polarsys.capella.cybersecurity.ui/src/org/polarsys/capella/cybersecurity/ui/contribution/migration/CybersecurityMigrationContribution.java
- during project migration
Change-Id: I2ded07ec0f7a16427bffabc05cc2df528c8b8b93
=> [569623] Check if cybersecurity viewpoint is activated

plugins/org.polarsys.capella.cybersecurity.sirius.analysis/src/org/polarsys/capella/cybersecurity/sirius/analysis/CybersecurityServices.java, tests/org.polarsys.capella.cybersecurity.test/src/org/polarsys/capella/cybersecurity/test/common/BasicDynamicModelTest.java, tests/org.polarsys.capella.cybersecurity.test/src/org/polarsys/capella/cybersecurity/test/diagram/CyberPABDiagramTest.java, tests/org.polarsys.capella.cybersecurity.test/src/org/polarsys/capella/cybersecurity/test/rules/testcases/cy_dcon/Rule_CY_DCON_02.java, tests/org.polarsys.capella.cybersecurity.test/src/org/polarsys/capella/cybersecurity/test/rules/testcases/cy_dcov/Rule_CY_DCOV_01.java, tests/org.polarsys.capella.cybersecurity.test/src/org/polarsys/capella/cybersecurity/test/rules/testcases/cy_dcov/Rule_CY_DCOV_02.java, tests/org.polarsys.capella.cybersecurity.test/src/org/polarsys/capella/cybersecurity/test/rules/testcases/cy_dcov/Rule_CY_DCOV_03.java, tests/org.polarsys.capella.cybersecurity.test/src/org/polarsys/capella/cybersecurity/test/rules/testcases/cy_dcov/Rule_CY_DCOV_04.java
Change-Id: I454c8b2311370ad21f09676ab2adcb4953af560a
=> [junits] Fix failing tests

plugins/org.polarsys.capella.cybersecurity.rcp/plugin.xml, plugins/org.polarsys.capella.cybersecurity.rcp/plugin_customization.ini
Bug: 568104
Change-Id: I671a6e36ee4d4e8b9a66ef0e4c9bb2eed8cfe360
Signed-off-by: Tu Ton <minhtutonthat@gmail.com>
=> [568104] Remove the contribution of the activity "Component Deployment" since it has been contributed in Capella

plugins/org.polarsys.capella.cybersecurity.model/src/org/polarsys/capella/cybersecurity/model/activator/CybersecurityModelActivator.java
Change-Id: I24e7b0d6c461b16d530a5e68ba7da98927ab89ee
=> [569623] On create config - check if cybersecurity vp is activated

plugins/org.polarsys.capella.cybersecurity.sirius.analysis/src/org/polarsys/capella/cybersecurity/sirius/analysis/CybersecurityServices.java, plugins/org.polarsys.capella.cybersecurity.ui/src/org/polarsys/capella/cybersecurity/ui/properties/sections/ThreatSection.java
Change-Id: I265a7da71c1d1a3a10ada7fc5a3602d586b9111a
=> [569870] Invalid feature name

Jenkinsfile
Change-Id: Id2fbbd75fd49971b5c632e9e2d90a02745aa1e8e
=> [config] Update config

plugins/org.polarsys.capella.cybersecurity.model.cdo/models/Cybersecurity.genmodel, plugins/org.polarsys.capella.cybersecurity.model.cdo/src/org/polarsys/capella/cybersecurity/model/impl/FunctionalPrimaryAssetImpl.java, plugins/org.polarsys.capella.cybersecurity.model.edit/src/org/polarsys/capella/cybersecurity/model/provider/FunctionalPrimaryAssetItemProvider.java, plugins/org.polarsys.capella.cybersecurity.model/models/Cybersecurity.ecore, plugins/org.polarsys.capella.cybersecurity.model/src/org/polarsys/capella/cybersecurity/model/FunctionalPrimaryAsset.java, plugins/org.polarsys.capella.cybersecurity.model/src/org/polarsys/capella/cybersecurity/model/impl/CybersecurityPackageImpl.java, plugins/org.polarsys.capella.cybersecurity.model/src/org/polarsys/capella/cybersecurity/model/impl/FunctionalPrimaryAssetImpl.java
Change-Id: I3f93870f57d6d83a8e635cf33eb4c3ce2cf5b265
=> #71 CDO fix to be able to add FunctionalChains in PrimaryAssets

plugins/org.polarsys.capella.cybersecurity.model/src/org/polarsys/capella/cybersecurity/model/activator/CybersecurityModelActivator.java, plugins/org.polarsys.capella.cybersecurity.ui/src/org/polarsys/capella/cybersecurity/ui/contribution/migration/CybersecurityMigrationContribution.java
- migration in Team4Capella
- migration after split of "Theft and data alteration"
Change-Id: I71744f947845340d970e726ab6f97a3fb257b232
=> #74 Fix migration issues

plugins/org.polarsys.capella.cybersecurity.ui/src/org/polarsys/capella/cybersecurity/ui/activity/predicate/IsViewpointActivatedPredicate.java
Bug: 568028
Change-Id: Iadef2312e11762e2f553442c1327de3f2e32e31b
Signed-off-by: Tu Ton <minhtutonthat@gmail.com>
=> [568028][Cybersecurity VP] Activity Explorer issue when updating activities with a VP contribution

Jenkinsfile
Change-Id: I7dbe5d5366f1b73118eda60605bcdac492370e53
=> #82 [releng] Fix windows product packaging

plugins/org.polarsys.capella.cybersecurity.ui/src/org/polarsys/capella/cybersecurity/ui/activity/predicate/IsViewpointActivatedPredicate.java
Change-Id: Ibe3a49e18493204073726220e5e0441f7a17fbf6
=> #89 Fix display in Activity Explorer of Cybersecurity vp
